name: PlatformIO CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out this repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install Python dependencies via Pipenv
        run: |
          pipenv install --deploy --dev

      - name: Install PIO projet libraries
        run: |
          pipenv run pio lib install

      - name: Build Nanopb protobuf compiler
        run: |
          cd .pio/libdeps/dev-esp32/Nanopb/generator/proto
          make

      - name: Build protobuf headers
        run: |
            cd src;
            pipenv run python ../.pio/libdeps/dev-esp32/Nanopb/generator/protoc --python_out=client/ --nanopb_out=. rfquack.proto
      
      - name: Build PIO project
        run: |
          pipenv run pio run